/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>
using namespace cv;
using namespace std;

#ifndef _Included_com_maria_patrunjel_smartimageeditor_MyImageProcessing
#define _Included_com_maria_patrunjel_smartimageeditor_MyImageProcessing
#ifdef __cplusplus
#define JNICALL
extern "C" {
#endif
/*
 * Class:     com_maria_patrunjel_smartimageeditor_MyImageProcessing
 * Method:    darkFilter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_maria_patrunjel_smartimageeditor_MyImageProcessing_darkFilter
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_maria_patrunjel_smartimageeditor_MyImageProcessing
 * Method:    brightFilter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_maria_patrunjel_smartimageeditor_MyImageProcessing_brightFilter
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_maria_patrunjel_smartimageeditor_MyImageProcessing
 * Method:    redFilter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_maria_patrunjel_smartimageeditor_MyImageProcessing_redFilter
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_maria_patrunjel_smartimageeditor_MyImageProcessing
 * Method:    greenFilter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_maria_patrunjel_smartimageeditor_MyImageProcessing_greenFilter
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_maria_patrunjel_smartimageeditor_MyImageProcessing
 * Method:    blueFilter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_maria_patrunjel_smartimageeditor_MyImageProcessing_blueFilter
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_maria_patrunjel_smartimageeditor_MyImageProcessing
 * Method:    binarizationFilter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_maria_patrunjel_smartimageeditor_MyImageProcessing_binarizationFilter
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_maria_patrunjel_smartimageeditor_MyImageProcessing
 * Method:    changeRGBChannels
 * Signature: (JJIII)V
 */
JNIEXPORT void JNICALL Java_com_maria_patrunjel_smartimageeditor_MyImageProcessing_changeRGBChannels
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint);

/*
 * Class:     com_maria_patrunjel_smartimageeditor_MyImageProcessing
 * Method:    changeContrastAndBrightness
 * Signature: (JJFF)V
 */
JNIEXPORT void JNICALL Java_com_maria_patrunjel_smartimageeditor_MyImageProcessing_changeContrastAndBrightness
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
